### ISSUE TITLE
Enable image caching for CI test step

### ISSUE THREAD

**Issue by thiras** [depremguvenligi/binabilgi#4]
The current setup takes ~3 min to complete. Most of the time is spent on image pulling. Image caching can improve the performance of the step significantly.

**Comment by yamac-kurtulus** [comment]
Bunu araştırdım biraz. En iyisi kullanmadığımız parçaları "-x" ile devre dışı bırakmak gibi. Cache'ten yüklemenin daha yavaş olduğunu yazmışlar burada, ki muhtemelen doğru olabilir:

https://github.com/supabase/setup-cli/issues/88#issuecomment-1370519155

**Comment by thiras** [comment]
Thank you very much. I'm closing the issue. The tests are clear in the issue.
